export const BasicInfoConstant = {
    COMPINFO_SUCCESS: 'COMPANY_INFO_SUCCESS',
    USER_ACCESS_FORM_SUCCESS: 'USER_ACCESS_FORM_SUCCESS',
    GET_FORM_INFO_SUCCESS:'GET_FORM_INFO_SUCCESS',
    GET_GRID_ROW_DATA_SUCCESS:'GET_GRID_ROW_DATA_SUCCESS',
    GET_SELECTED_FORM_ID:'GET_SELECTED_FORM_ID'
};
